name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Publish Solution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Extend PackageVersion with build number in Directory.Build.props
      shell: pwsh
      run: |
        Write-Host ''New version uses build number ${$env:GITHUB_RUN_NUMBER}''
        (Get-Content Directory.Build.props) -replace ''(<PackageVersion>\d+\.\d+\.\d+\.)(\d+)(</PackageVersion>)'', ''${1}${$env:GITHUB_RUN_NUMBER}${3}'' | Out-File Directory.Build.props
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --no-build -c Release
    - name: Upload Packages as artifacts
      uses: actions/upload-artifact@v3.0.0
      with:
        name: packages
        path: '**/*.nupkg'
      
